- name: Kubernetes Setup
  hosts: all
  become: true
  vars:
    pod_network_cidr: "{{ hostvars[inventory_hostname].ansible_host | default(ansible_default_ipv4.address) | regex_replace('\\.\\d+\\.\\d+$', '.0.0') }}/16"
  tasks:
    - name: Debug variables
      debug:
        msg:
          - "Node: {{ inventory_hostname }}"
          - "IP Address: {{ hostvars[inventory_hostname].ansible_host | default(ansible_default_ipv4.address) }}"
          - "Pod Network CIDR: {{ pod_network_cidr }}"

    - include_role:
        name: hostname
    - include_role:
        name: prerequisites
    - include_role:
        name: firewall
    - include_role:
        name: repos
    - include_role:
        name: install_packages
    #- include_role:
    #    name: kubeadm
