- name: Kubernetes Setup
  hosts: all
  become: true
  vars:
    pod_network_cidr: "{{ ansible_host | default(ansible_default_ipv4.address) }}/16"  # Calcula automáticamente la IP
  tasks:
    - name: Debug variables
      debug:
        msg:
          - "Node: {{ inventory_hostname }}"
          - "IP Address: {{ ansible_host | default(ansible_default_ipv4.address) }}"
          - "Pod Network CIDR: {{ pod_network_cidr }}"

    - include_role:
        name: hostname
    - include_role:
        name: prerequisites
    - include_role:
        name: firewall
    - include_role:
        name: repos
    - include_role:
        name: install_packages
    - include_role:
        name: kubeadm
