- name: Disable swap
  command: swapoff -a

- name: Load kernel modules
  shell: |
    modprobe ip_tables iptable_nat
    modprobe kvm
    chmod 666 /dev/kvm
    usermod -aG kvm $USER
    modprobe overlay
    modprobe br_netfilter
    sysctl -w net.ipv4.ip_forward=1

- name: Configure modules
  copy:
    dest: /etc/modules-load.d/kubernetes.conf
    content: |
      br_netfilter
      ip_vs
      ip_vs_rr
      ip_vs_wrr
      ip_vs_sh
      overlay

- name: Configure sysctl
  copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Apply sysctl settings
  command: sysctl --system

- name: Initialize Kubernetes cluster
  command: kubeadm init --control-plane-endpoint {{ hostvars[inventory_hostname].ansible_host | default(ansible_default_ipv4.address) }}:6443 --cri-socket=unix:///var/run/crio/crio.sock


- name: Configure kubectl for the root user
  shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config


- name: Install Helm
  shell: |
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh

- name: Install Cilium CLI
  shell: |
    CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
    GOOS=$(go env GOOS)
    GOARCH=$(go env GOARCH)
    curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-${GOOS}-${GOARCH}.tar.gz{,.sha256sum}
    sha256sum --check cilium-${GOOS}-${GOARCH}.tar.gz.sha256sum
    sudo tar -C /usr/local/bin -xzvf cilium-${GOOS}-${GOARCH}.tar.gz
    rm cilium-${GOOS}-${GOARCH}.tar.gz{,.sha256sum}
    cilium install
    
# Set kubectl completion and alias
- name: Set kubectl completion in bash
  shell: echo "source <(kubectl completion bash)" >> ~/.bashrc

- name: Set kubectl alias in bash
  shell: echo "alias k=kubectl" >> ~/.bashrc

- name: Set kubectl auto-completion
  shell: echo "complete -o default -F __start_kubectl k" >> ~/.bashrc


- name: Source bashrc for kubectl completion
  shell: source ~/.bashrc

# Disable swap on Kubelet
- name: Set failSwapOn to false in kubelet config
  lineinfile:
    path: /var/lib/kubelet/config.yaml
    line: 'failSwapOn: false'
    create: yes
    state: present

# Verify nodes in Kubernetes
- name: Get Kubernetes nodes
  command: kubectl get nodes
