- name: Disable swap
  command: swapoff -a

- name: Load kernel modules
  shell: |
    modprobe ip_tables iptable_nat
    modprobe kvm
    chmod 666 /dev/kvm
    usermod -aG kvm $USER
    modprobe br_netfilter
    sysctl -w net.ipv4.ip_forward=1

- name: Configure modules
  copy:
    dest: /etc/modules-load.d/kubernetes.conf
    content: |
      br_netfilter
      ip_vs
      ip_vs_rr
      ip_vs_wrr
      ip_vs_sh
      overlay

- name: Configure sysctl
  copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Apply sysctl settings
  command: sysctl --system

- name: Initialize Kubernetes cluster
  command: kubeadm init --pod-network-cidr={{ pod_network_cidr }} --control-plane-endpoint {{ hostvars[inventory_hostname].ansible_host | default(ansible_default_ipv4.address) }}:6443 --cri-socket=unix:///var/run/crio/crio.sock