- name: Disable swap
  command: swapoff -a

- name: Load kernel modules
  shell: |
    modprobe ip_tables iptable_nat
    modprobe kvm
    chmod 666 /dev/kvm
    usermod -aG kvm $USER
    modprobe br_netfilter

- name: Configure sysctl
  copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Apply sysctl settings
  command: sysctl --system

- name: Initialize Kubernetes cluster
  command: kubeadm init --pod-network-cidr={{ pod_network_cidr }} --control-plane-endpoint {{ ansible_host | default(ansible_default_ipv4.address) }}:6443 --cri-socket=unix:///var/run/crio/crio.sock

