- name: Install required packages
  dnf:
    name:
      - container-selinux
      - cri-o
      - kubelet
      - kubeadm
      - kubectl

- name: Enable and start CRI-O service
  systemd:
    name: crio
    enabled: true
    state: started

- name: Enable and start Kubelet service
  systemd:
    name: kubelet
    enabled: true
    state: started