cilium_release: "1.14.0"
cilium_helm_values:
  externalIPs:
    enabled: true
  hostPort:
    enabled: true
  kubeProxyReplacement: true
  k8sServiceHost: "{{ ansible_facts['default_ipv4']['address'] }}"
  k8sServicePort: 6443
  loadBalancer:
    algorithm: maglev
  nodeinit:
    enabled: true
  nodePort:
    enabled: true
  operator:
    replicas: 1
  hubble:
    enabled: true
    metrics:
      enabled:
        - dns
        - drop
        - tcp
        - flow
        - port-distribution
        - icmp
        - http
    listenAddress: ":4244"
    relay:
      enabled: true
    ui:
      enabled: true